name: cross_sensors
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.2.0
  built_value: ^6.4.0
  cloud_firestore: ^0.10.0
  connectivity: ^0.4.3+1
  cupertino_icons: ^0.1.2
  firebase_core: ^0.3.4
  firebase_performance: ^0.1.1
  firebase: ^5.0.3
  path_provider: ^0.5.0+1
  sensors: ^0.4.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  build_runner: ^1.3.3
  built_value_generator: ^6.4.0

flutter:
  uses-material-design: true