name: cross_sensors
description: Read sensors data.

version: 1.0.0+1

environment:
  sdk: '>=2.3.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.2.2
  built_value: ^6.6.0
  cloud_firestore: ^0.12.5+1
  firebase_storage: ^3.0.1
  firebase_core: ^0.4.0+5
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0+1
  sensors: ^0.4.0+1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  build_runner: ^1.5.2
  built_value_generator: ^6.6.0

flutter:
  uses-material-design: true
